//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanıcılar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanıcılar()
        {
            this.KullaniciRolleri = new HashSet<KullaniciRolleri>();
            this.Sepet = new HashSet<Sepet>();
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Kullanıcı Adı alanı boş geçilemez")]
        [Display(Name = "Kullanıcı Adı")]
        public string KullanıcıAdi { get; set; }
        [Required(ErrorMessage = "Şifre alanı boş geçilemez")]
        [Display(Name = "Şifre")]
        public string Sifre { get; set; }
        public string Rol { get; set; }
        [Required(ErrorMessage = "Ad Soyad alanı boş geçilemez")]
        [Display(Name = "Ad Soyad")]
        public string AdiSoyadi { get; set; }
        [Required(ErrorMessage = "Telefon alanı boş geçilemez")]

        public string Telefon { get; set; }
        [Required(ErrorMessage = "Adres alanı boş geçilemez")]
        public string Adres { get; set; }
        [Required(ErrorMessage = "E-mail alanı boş geçilemez")]
        [Display(Name = "E-mail")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Tarih alanı boş geçilemez")]
        public System.DateTime Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciRolleri> KullaniciRolleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
