//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Markalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Markalar()
        {
            this.Ürünler = new HashSet<Ürünler>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Kategori alanı boş geçilemez")]
        [Display(Name = "Kategori")]
        public int KategoriID { get; set; }
        [Required(ErrorMessage = "Markalar alanı boş geçilemez")]
        [Display(Name = "Markaslar")]
        public string Markalar1 { get; set; }
        [Required(ErrorMessage = "Açıklama alanı boş geçilemez")]
        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ürünler> Ürünler { get; set; }
    }
}
