//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int ID { get; set; }
        public int UrunID { get; set; }
        public int KullaniciID { get; set; }
        public decimal AlisFiyat { get; set; }
        public decimal BirimMiktar { get; set; }
        public decimal ToplamFiyat { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.DateTime Saat { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual Ürünler Ürünler { get; set; }
    }
}
