//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Ürünler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ürünler()
        {
            this.Sepet = new HashSet<Sepet>();
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Kategori alanı boş geçilemez")]
        [Display(Name = "Kategori")]
        public int KategoriID { get; set; }
        [Required(ErrorMessage = "Marka alanı boş geçilemez")]
        [Display(Name = "Marka")]
        public int MarkaID { get; set; }
        [Required(ErrorMessage = "Barkod No alanı boş geçilemez")]
        [Display(Name = "Barkod No")]
        public string BarkodNo { get; set; }
        [Required(ErrorMessage = "Ürün adı alanı boş geçilemez")]
        [Display(Name = "Ürün Adı")]
        public string UrunAdı { get; set; }
        [Required(ErrorMessage = "Alış fıyatı alanı boş geçilemez")]
        [Display(Name = "Alış Fiyatı")]
        public decimal AlisFiyat { get; set; }
        [Required(ErrorMessage = "Satış fiyatı boş geçilemez")]
        [Display(Name = "Satış Fiyatı")]
        public decimal SatisFiyat { get; set; }
        [Required(ErrorMessage = "Miktar alanı boş geçilemez")]

        public decimal Miktarı { get; set; }
        [Required(ErrorMessage = "KDV alanı boş geçilemez")]
        public int KDV { get; set; }
        [Required(ErrorMessage = "Birim alanı boş geçilemez")]
        [Display(Name = "Birim")]
        public int BirimID { get; set; }
        [Required(ErrorMessage = "Tarih alanı boş geçilemez")]
        public System.DateTime Tarih { get; set; }
        [Required(ErrorMessage = "Açıklama alanı boş geçilemez")]
        [Display(Name = "Açıklama")]
        public string Aciklama { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }

        public List<SelectListItem> KategoriListesi { get; set; }
        public List<SelectListItem> MarkaListesi { get; set; }
        public List<SelectListItem> BirimListesi { get; set; }
    }
}
